# Generated by Django 6.0.1 on 2026-02-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_category_delete_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
