# Generated by Django 6.0.1 on 2026-02-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
