# Generated by Django 6.0.1 on 2026-02-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category/default.png', upload_to='category/'),
        ),
    ]
