# Generated by Django 6.0.1 on 2026-03-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='categoryId',
        ),
    ]
