# Generated by Django 6.0.1 on 2026-04-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
