# Generated by Django 6.0.1 on 2026-04-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_alter_about_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='about',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='about',
            name='why_choose_us',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
