# Generated by Django 6.0.1 on 2026-04-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_remove_about_created_at_remove_about_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='why_choose_us',
            field=models.JSONField(default=list),
        ),
    ]
