# Generated by Django 6.0.1 on 2026-04-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0012_alter_about_title_alter_about_why_choose_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='why_choose_us',
        ),
    ]
