# Generated by Django 6.0.1 on 2026-04-08 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_remove_about_why_choose_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calc.category'),
        ),
    ]
