# Generated by Django 6.0.1 on 2026-04-08 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_alter_item_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calc.category'),
        ),
    ]
