# Generated by Django 6.0.1 on 2026-06-03 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0018_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.client'),
        ),
    ]
