# Generated by Django 6.0.1 on 2026-06-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0020_item_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='client',
        ),
        migrations.RemoveField(
            model_name='category',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
