# Generated by Django 6.0.1 on 2026-06-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0025_contact_restaurant_restaurant_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
