# Generated by Django 6.0.1 on 2026-06-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0026_delete_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='restaurant',
        ),
    ]
