# Generated by Django 6.0.1 on 2026-06-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0030_category_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='restaurant',
        ),
    ]
